# region imports
try:
    from AlgorithmImports import *
except ImportError:
    pass
# endregion
"""ON-B7 Shadow Monitor — Theoretical position tracker for multi-instance mode.

Tracks ALL signals generated by B6 as "shadow positions" — lightweight entries
that monitor market data against TP/SL levels without placing real orders.

When a signal is TAKEN (real trade), its shadow is removed (real B7 supersedes).
When a signal is SKIPPED or PARITY_SKIPPED, the shadow monitors the market and
publishes a theoretical trade outcome when TP or SL is hit.

These theoretical outcomes feed into the Offline Category A learning path
(DMA, EWMA, Kelly, BOCPD) so that both instances in a multi-instance setup
learn from the same signal universe, keeping strategy parameters synchronized.

Reads: Live market data (quote_cache from TopstepX stream)
Writes: stream:signal_outcomes (theoretical trade outcomes for Offline)
"""

import json
import logging
import uuid
from datetime import datetime

from shared.questdb_client import get_cursor
from shared.redis_client import publish_to_stream, STREAM_SIGNAL_OUTCOMES
from shared.topstep_stream import quote_cache
from shared.contract_resolver import resolve_contract_id

logger = logging.getLogger(__name__)

# Maximum age (seconds) before a shadow position expires without resolution
SHADOW_MAX_AGE_SECONDS = 8 * 3600  # 8 hours — covers full trading session


def register_shadow_position(signal: dict, session_id: int) -> dict:
    """Create a shadow position entry from a B6 signal.

    Called by the Online orchestrator for every signal generated,
    regardless of whether it will be TAKEN or SKIPPED.

    Returns a shadow position dict for tracking.
    """
    return {
        "signal_id": signal.get("signal_id", f"SIG-{uuid.uuid4().hex[:12].upper()}"),
        "asset": signal.get("asset"),
        "direction": signal.get("direction", 0),
        "entry_price": signal.get("tp_level") and signal.get("sl_level") and _infer_entry(signal),
        "tp_level": signal.get("tp_level"),
        "sl_level": signal.get("sl_level"),
        "point_value": _get_point_value(signal.get("asset")),
        "contracts": _get_shadow_contracts(signal),
        "session": session_id,
        "regime_state": signal.get("regime_state"),
        "combined_modifier": signal.get("combined_modifier", 1.0),
        "aim_breakdown": signal.get("aim_breakdown"),
        "user_id": signal.get("user_id", "primary_user"),
        "created_at": datetime.now(),
        "resolved": False,
    }


def monitor_shadow_positions(shadow_positions: list[dict]) -> list[dict]:
    """Single monitoring pass for all shadow positions.

    Checks live market prices against TP/SL levels. Resolves and publishes
    theoretical outcomes for any positions that hit their targets.

    Returns list of resolved shadow positions (to be removed from tracking).
    """
    resolved = []

    for shadow in shadow_positions:
        if shadow.get("resolved"):
            resolved.append(shadow)
            continue

        # Skip if no valid direction (OR not yet resolved)
        direction = shadow.get("direction", 0)
        if direction == 0:
            continue

        # Expire stale shadows — publish TIMEOUT outcome for Offline learning
        age = (datetime.now() - shadow["created_at"]).total_seconds()
        if age > SHADOW_MAX_AGE_SECONDS:
            exit_price = _get_live_price(shadow["asset"]) or shadow.get("entry_price", 0)
            _resolve_shadow(shadow, "TIMEOUT", exit_price)
            resolved.append(shadow)
            logger.info("Shadow TIMEOUT: %s %s (age=%ds)",
                        shadow["signal_id"], shadow["asset"], int(age))
            continue

        # Get live price
        current_price = _get_live_price(shadow["asset"])
        if current_price is None:
            continue

        tp = shadow.get("tp_level")
        sl = shadow.get("sl_level")

        # Check TP hit
        if tp is not None:
            if (direction == 1 and current_price >= tp) or \
               (direction == -1 and current_price <= tp):
                _resolve_shadow(shadow, "TP_HIT", current_price)
                resolved.append(shadow)
                continue

        # Check SL hit
        if sl is not None:
            if (direction == 1 and current_price <= sl) or \
               (direction == -1 and current_price >= sl):
                _resolve_shadow(shadow, "SL_HIT", current_price)
                resolved.append(shadow)
                continue

    return resolved


def _resolve_shadow(shadow: dict, outcome: str, exit_price: float):
    """Resolve a shadow position and publish theoretical outcome.

    Publishes to stream:signal_outcomes for Offline Category A learning.
    The theoretical outcome has the same schema as a real trade outcome
    but is flagged as theoretical=True so CB params (Category B) ignore it.
    """
    shadow["resolved"] = True

    direction = shadow.get("direction", 1)
    entry_price = shadow.get("entry_price", 0)
    contracts = shadow.get("contracts", 1)
    point_value = shadow.get("point_value", 50.0)

    if entry_price is None or entry_price == 0:
        logger.warning("Shadow resolve skipped — no entry price for %s", shadow["signal_id"])
        return

    gross_pnl = (exit_price - entry_price) * direction * contracts * point_value

    theoretical_outcome = {
        "trade_id": f"SHADOW-{uuid.uuid4().hex[:12].upper()}",
        "signal_id": shadow["signal_id"],
        "user_id": shadow.get("user_id", "primary_user"),
        "asset": shadow["asset"],
        "direction": direction,
        "entry_price": entry_price,
        "exit_price": exit_price,
        "contracts": contracts,
        "pnl": gross_pnl,  # No commission for theoretical trades
        "commission": 0,
        "slippage": None,
        "outcome": outcome,
        "regime_at_entry": shadow.get("regime_state"),
        "aim_modifier_at_entry": shadow.get("combined_modifier"),
        "aim_breakdown_at_entry": shadow.get("aim_breakdown"),
        "session": shadow.get("session"),
        "theoretical": True,  # Category B blocks (CB params) must ignore this
        "timestamp": datetime.now().isoformat(),
    }

    try:
        publish_to_stream(STREAM_SIGNAL_OUTCOMES, theoretical_outcome)
        logger.info("Shadow resolved: %s %s %s pnl=%.2f (theoretical)",
                     shadow["asset"], outcome, shadow["signal_id"], gross_pnl)
    except Exception as e:
        logger.error("Failed to publish shadow outcome %s: %s", shadow["signal_id"], e)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _infer_entry(signal: dict) -> float | None:
    """Infer entry price from signal features or per_account data."""
    # Direct entry price from OR tracker
    features = signal.get("features", {})
    if isinstance(features, dict) and features.get("entry_price"):
        return float(features["entry_price"])

    # From per_account — take first account's entry if available
    per_account = signal.get("per_account", {})
    for ac_id, ac_detail in per_account.items():
        if isinstance(ac_detail, dict) and ac_detail.get("entry_price"):
            return float(ac_detail["entry_price"])

    # Compute from TP/SL midpoint as last resort (ORB strategy: entry is between TP and SL)
    tp = signal.get("tp_level")
    sl = signal.get("sl_level")
    direction = signal.get("direction", 0)
    if tp is not None and sl is not None and direction != 0:
        # For ORB: entry divides TP-SL range at sl_multiple/(tp_multiple+sl_multiple)
        # Default tp_multiple=0.70, sl_multiple=0.35 → entry is 1/3 from SL toward TP
        # Simpler: entry = SL + (TP-SL) * sl_frac where sl_frac = 0.35/(0.35+0.70) = 1/3
        if direction == 1:
            return sl + (tp - sl) / 3.0
        else:
            return tp + (sl - tp) / 3.0

    return None


def _get_shadow_contracts(signal: dict) -> int:
    """Get contract count from signal's per_account breakdown."""
    per_account = signal.get("per_account", {})
    for ac_id, ac_detail in per_account.items():
        if isinstance(ac_detail, dict):
            contracts = ac_detail.get("contracts", 0)
            if contracts > 0:
                return contracts
    return 1  # Default to 1 for per-contract normalization


def _get_point_value(asset_id: str) -> float:
    """Get point value for asset from D00 (used for P&L calculation)."""
    try:
        with get_cursor() as cur:
            cur.execute(
                "SELECT point_value FROM asset_universe "
                "LATEST ON ts PARTITION BY asset_id "
                "WHERE asset_id = $1",
                [asset_id],
            )
            row = cur.fetchone()
            if row and row[0] is not None:
                return float(row[0])
    except Exception:
        logger.warning("_get_point_value: D00 lookup failed for %s, using default 50.0", asset_id)
    return 50.0


def _get_live_price(asset_id: str) -> float | None:
    """Get live price from TopstepX stream cache."""
    contract_id = resolve_contract_id(asset_id)
    if not contract_id:
        return None
    quote = quote_cache.get(contract_id)
    if quote and quote.get("lastPrice"):
        return float(quote["lastPrice"])
    return None
